basePath: /api/v1
definitions:
  domain.Event:
    properties:
      character_id:
        type: integer
      dice_roll:
        type: boolean
      difficulty_class:
        type: boolean
      environment:
        type: string
      event_description:
        type: string
      event_id:
        type: integer
      session_id:
        type: integer
      type:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  domain.UserLoginInfo:
    properties:
      idToken:
        type: string
    type: object
  domain.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  dto.CreateEventDto:
    properties:
      Environment:
        type: string
      character_id:
        type: integer
      dice_roll:
        type: boolean
      difficulty_class:
        type: boolean
      event_description:
        type: string
      session_id:
        type: integer
      type:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API endpoints documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Dicelogger API
  version: "1.0"
paths:
  /event:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all events
      tags:
      - event
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateEventDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateEventDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create event
      tags:
      - event
  /event/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete event
      tags:
      - event
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by id
      tags:
      - event
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: CreateEventDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateEventDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update event
      tags:
      - event
  /event/character/{id}:
    get:
      parameters:
      - description: character_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by character id
      tags:
      - event
  /event/session/{id}:
    get:
      parameters:
      - description: session_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by session id
      tags:
      - event
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserResponse'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all users
      tags:
      - user
  /user/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete user
      tags:
      - user
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user by id
      tags:
      - user
    patch:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Partially update user
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: UserLoginInfo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserLoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Login user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.UserResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Register user
      tags:
      - user
swagger: "2.0"
