basePath: /api/v1
definitions:
  domain.Campaign:
    properties:
      campaign_id:
        type: integer
      description:
        type: string
      dungeon_master:
        type: integer
      image:
        type: string
      name:
        type: string
    type: object
  domain.Event:
    properties:
      character_id:
        type: integer
      dice_roll:
        type: boolean
      difficulty_class:
        type: boolean
      environment:
        type: string
      event_description:
        type: string
      event_id:
        type: integer
      session_id:
        type: integer
      type:
        type: string
    type: object
  domain.Session:
    properties:
      campaign_id:
        type: integer
      description:
        type: string
      end:
        type: string
      session_id:
        type: integer
      start:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  domain.UserCampaign:
    properties:
      campaign_id:
        type: integer
      is_dm:
        type: integer
      is_owner:
        type: integer
      user_campaign_id:
        type: integer
      user_id:
        type: string
    type: object
  domain.UserLoginInfo:
    properties:
      idToken:
        type: string
    type: object
  domain.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  dto.CreateCampaignDto:
    properties:
      description:
        type: string
      dungeon_master:
        type: integer
      image:
        type: string
      name:
        type: string
    type: object
  dto.CreateEventDto:
    properties:
      Environment:
        type: string
      character_id:
        type: integer
      dice_roll:
        type: boolean
      difficulty_class:
        type: boolean
      event_description:
        type: string
      session_id:
        type: integer
      type:
        type: string
    type: object
  dto.CreateSessionDto:
    properties:
      campaign_id:
        type: integer
      description:
        type: string
      end:
        type: string
      start:
        type: string
    type: object
  dto.CreateUserCampaignDto:
    properties:
      campaign_id:
        type: integer
      is_dm:
        type: integer
      is_owner:
        type: integer
      user_id:
        type: string
    type: object
  dto.ResponseCampaignDto:
    properties:
      description:
        type: string
      dungeon_master:
        type: integer
      image:
        type: string
      name:
        type: string
      sessions:
        items:
          $ref: '#/definitions/domain.Session'
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API endpoints documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Dicelogger API
  version: "1.0"
paths:
  /campaign:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ResponseCampaignDto'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all campaigns
      tags:
      - campaign
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateCampaignDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCampaignDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Campaign'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create campaign
      tags:
      - campaign
  /campaign/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete campaign
      tags:
      - campaign
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseCampaignDto'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get campaign by id
      tags:
      - campaign
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: CreateCampaignDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCampaignDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseCampaignDto'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update campaign
      tags:
      - campaign
  /campaign/user/{id}:
    get:
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ResponseCampaignDto'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get campaigns by user id
      tags:
      - campaign
  /event:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all events
      tags:
      - event
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateEventDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateEventDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create event
      tags:
      - event
  /event/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete event
      tags:
      - event
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by id
      tags:
      - event
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: CreateEventDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateEventDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update event
      tags:
      - event
  /event/character/{id}:
    get:
      parameters:
      - description: character_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by character id
      tags:
      - event
  /event/session/{id}:
    get:
      parameters:
      - description: session_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Event'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get event by session id
      tags:
      - event
  /session:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Session'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all sessions
      tags:
      - session
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateSessionDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateSessionDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Session'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create session
      tags:
      - session
  /session/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete session
      tags:
      - session
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Session'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get session by id
      tags:
      - session
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: CreateSessionDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateSessionDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Session'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update session
      tags:
      - session
  /session/campaign/{id}:
    get:
      parameters:
      - description: campaign_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Session'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get session by campaign id
      tags:
      - session
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserResponse'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all users
      tags:
      - user
  /user/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete user
      tags:
      - user
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user by id
      tags:
      - user
    patch:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Partially update user
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: UserLoginInfo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserLoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Login user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.UserResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Register user
      tags:
      - user
  /user_campaign:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserCampaign'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all user_campaign
      tags:
      - user_campaign
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateUserCampaignDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserCampaignDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.UserCampaign'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create user_campaign
      tags:
      - user_campaign
  /user_campaign/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete user_campaign
      tags:
      - user_campaign
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserCampaign'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user_campaign by id
      tags:
      - user_campaign
  /user_campaign/campaign/{id}:
    get:
      parameters:
      - description: campaign_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserCampaign'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user_campaign by campaign id
      tags:
      - user_campaign
  /user_campaign/user/{id}:
    get:
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserCampaign'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user_campaign by user id
      tags:
      - user_campaign
swagger: "2.0"
